// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package blockstore

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN.String() && e.Code == 500
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func IsIpldNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IPLD_NOT_FOUND.String() && e.Code == 500
}

func ErrorIpldNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_IPLD_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
