// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: app/provide/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_provide_internal_conf_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_provide_internal_conf_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_provide_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kafka          *Kafka   `protobuf:"bytes,1,opt,name=kafka,proto3" json:"kafka,omitempty"`
	NodeAddr       []string `protobuf:"bytes,2,rep,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	BlockstoreUri  string   `protobuf:"bytes,3,opt,name=blockstore_uri,json=blockstoreUri,proto3" json:"blockstore_uri,omitempty"`
	EnableProvider bool     `protobuf:"varint,4,opt,name=enable_provider,json=enableProvider,proto3" json:"enable_provider,omitempty"`
	PinSet         *Pg      `protobuf:"bytes,5,opt,name=pin_set,json=pinSet,proto3" json:"pin_set,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_provide_internal_conf_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_provide_internal_conf_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_app_provide_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetKafka() *Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

func (x *Data) GetNodeAddr() []string {
	if x != nil {
		return x.NodeAddr
	}
	return nil
}

func (x *Data) GetBlockstoreUri() string {
	if x != nil {
		return x.BlockstoreUri
	}
	return ""
}

func (x *Data) GetEnableProvider() bool {
	if x != nil {
		return x.EnableProvider
	}
	return false
}

func (x *Data) GetPinSet() *Pg {
	if x != nil {
		return x.PinSet
	}
	return nil
}

type Pg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable     string `protobuf:"bytes,1,opt,name=enable,proto3" json:"enable,omitempty"`
	SourcesDsn string `protobuf:"bytes,2,opt,name=sourcesDsn,proto3" json:"sourcesDsn,omitempty"`
}

func (x *Pg) Reset() {
	*x = Pg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_provide_internal_conf_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pg) ProtoMessage() {}

func (x *Pg) ProtoReflect() protoreflect.Message {
	mi := &file_app_provide_internal_conf_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pg.ProtoReflect.Descriptor instead.
func (*Pg) Descriptor() ([]byte, []int) {
	return file_app_provide_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Pg) GetEnable() string {
	if x != nil {
		return x.Enable
	}
	return ""
}

func (x *Pg) GetSourcesDsn() string {
	if x != nil {
		return x.SourcesDsn
	}
	return ""
}

type Kafka struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  []string `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
	Topic string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Group string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_provide_internal_conf_conf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_app_provide_internal_conf_conf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_app_provide_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Kafka) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Kafka) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Kafka) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

var File_app_provide_internal_conf_conf_proto protoreflect.FileDescriptor

var file_app_provide_internal_conf_conf_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x35, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcd, 0x01,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x05, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x4b, 0x61, 0x66, 0x6b, 0x61, 0x52, 0x05, 0x6b, 0x61,
	0x66, 0x6b, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x25, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x75,
	0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x55, 0x72, 0x69, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x50, 0x67, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x22, 0x3c, 0x0a,
	0x02, 0x50, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x44, 0x73, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x44, 0x73, 0x6e, 0x22, 0x47, 0x0a, 0x05, 0x4b,
	0x61, 0x66, 0x6b, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x26, 0x5a, 0x24, 0x69, 0x70, 0x66, 0x73, 0x2d, 0x74, 0x6f, 0x70,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_provide_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_provide_internal_conf_conf_proto_rawDescData = file_app_provide_internal_conf_conf_proto_rawDesc
)

func file_app_provide_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_provide_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_provide_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_provide_internal_conf_conf_proto_rawDescData)
	})
	return file_app_provide_internal_conf_conf_proto_rawDescData
}

var file_app_provide_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_app_provide_internal_conf_conf_proto_goTypes = []interface{}{
	(*Bootstrap)(nil), // 0: ipfs.node.conf.Bootstrap
	(*Data)(nil),      // 1: ipfs.node.conf.Data
	(*Pg)(nil),        // 2: ipfs.node.conf.Pg
	(*Kafka)(nil),     // 3: ipfs.node.conf.Kafka
}
var file_app_provide_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: ipfs.node.conf.Bootstrap.data:type_name -> ipfs.node.conf.Data
	3, // 1: ipfs.node.conf.Data.kafka:type_name -> ipfs.node.conf.Kafka
	2, // 2: ipfs.node.conf.Data.pin_set:type_name -> ipfs.node.conf.Pg
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_provide_internal_conf_conf_proto_init() }
func file_app_provide_internal_conf_conf_proto_init() {
	if File_app_provide_internal_conf_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_provide_internal_conf_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_provide_internal_conf_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_provide_internal_conf_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_provide_internal_conf_conf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kafka); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_provide_internal_conf_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_provide_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_provide_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_app_provide_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_provide_internal_conf_conf_proto = out.File
	file_app_provide_internal_conf_conf_proto_rawDesc = nil
	file_app_provide_internal_conf_conf_proto_goTypes = nil
	file_app_provide_internal_conf_conf_proto_depIdxs = nil
}
