// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/4everland/ipfs-servers/app/node/biz/provide"
	"github.com/4everland/ipfs-servers/app/node/conf"
	"github.com/4everland/ipfs-servers/app/node/data"
	"github.com/4everland/ipfs-servers/app/node/server"
	"github.com/4everland/ipfs-servers/app/node/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	batching, err := data.NewLevelDbDatastore(confServer)
	if err != nil {
		return nil, nil, err
	}
	blockstore := data.NewBlockStore(confData)
	bitSwapService := service.NewBitSwapService(blockstore)
	queue, err := provide.ProviderQueue(batching)
	if err != nil {
		return nil, nil, err
	}
	v := provide.SimpleProvider(queue)
	keyChanFunc := data.NewKeyChanFunc(blockstore)
	v2, err := provide.SimpleReprovider(confData, keyChanFunc)
	if err != nil {
		return nil, nil, err
	}
	routingService := service.NewRoutingService(bitSwapService, v, v2)
	v3 := service.NewNodeServices(bitSwapService, routingService)
	nodeServer, err := server.NewNodeServer(confServer, logger, batching, v3...)
	if err != nil {
		return nil, nil, err
	}
	grpcServer := server.NewContentRoutingGRPCServer(confServer, routingService, logger)
	app := newApp(logger, nodeServer, grpcServer)
	return app, func() {
	}, nil
}
