// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/4everland/ipfs-servers/app/node/conf"
	"github.com/4everland/ipfs-servers/app/node/server"
	"github.com/4everland/ipfs-servers/app/node/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	blockstore := service.NewBlockStore(data)
	bitSwapService := service.NewBitSwapService(blockstore)
	v := service.NewNodeServices(bitSwapService)
	nodeServer, err := server.NewNodeServer(confServer, logger, v...)
	if err != nil {
		return nil, nil, err
	}
	contentRoutingService := service.NewContentRoutingService()
	grpcServer := server.NewContentRoutingGRPCServer(confServer, contentRoutingService, logger)
	app := newApp(logger, nodeServer, grpcServer)
	return app, func() {
	}, nil
}
