// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/4everland/ipfs-servers/app/blockstore/biz"
	"github.com/4everland/ipfs-servers/app/blockstore/conf"
	"github.com/4everland/ipfs-servers/app/blockstore/server"
	"github.com/4everland/ipfs-servers/app/blockstore/services"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	blockStore := biz.NewBackendStorage(data, logger)
	blockIndex := biz.NewIndexStore(data)
	blockstoreService := services.NewBlockstoreService(blockStore, blockIndex)
	grpcServer := server.NewGRPCServer(confServer, blockstoreService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
