// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/pin/pin.proto

package pin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive bool   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *AddReq) Reset() {
	*x = AddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReq) ProtoMessage() {}

func (x *AddReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReq.ProtoReflect.Descriptor instead.
func (*AddReq) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{0}
}

func (x *AddReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddReq) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type LsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *LsReq) Reset() {
	*x = LsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsReq) ProtoMessage() {}

func (x *LsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsReq.ProtoReflect.Descriptor instead.
func (*LsReq) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{1}
}

func (x *LsReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type IsPinnedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	WithType string `protobuf:"bytes,2,opt,name=withType,proto3" json:"withType,omitempty"`
}

func (x *IsPinnedReq) Reset() {
	*x = IsPinnedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPinnedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPinnedReq) ProtoMessage() {}

func (x *IsPinnedReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPinnedReq.ProtoReflect.Descriptor instead.
func (*IsPinnedReq) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{2}
}

func (x *IsPinnedReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IsPinnedReq) GetWithType() string {
	if x != nil {
		return x.WithType
	}
	return ""
}

type RmReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive bool   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
}

func (x *RmReq) Reset() {
	*x = RmReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmReq) ProtoMessage() {}

func (x *RmReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmReq.ProtoReflect.Descriptor instead.
func (*RmReq) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{3}
}

func (x *RmReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RmReq) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type UpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form  string `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
	To    string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Unpin bool   `protobuf:"varint,3,opt,name=unpin,proto3" json:"unpin,omitempty"`
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetForm() string {
	if x != nil {
		return x.Form
	}
	return ""
}

func (x *UpdateReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *UpdateReq) GetUnpin() bool {
	if x != nil {
		return x.Unpin
	}
	return false
}

type IsPinnedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	IsPinned bool   `protobuf:"varint,2,opt,name=isPinned,proto3" json:"isPinned,omitempty"`
}

func (x *IsPinnedResp) Reset() {
	*x = IsPinnedResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPinnedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPinnedResp) ProtoMessage() {}

func (x *IsPinnedResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPinnedResp.ProtoReflect.Descriptor instead.
func (*IsPinnedResp) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{5}
}

func (x *IsPinnedResp) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *IsPinnedResp) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type PinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PinType string `protobuf:"bytes,1,opt,name=pinType,proto3" json:"pinType,omitempty"`
	Cid     string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Err     string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *PinInfo) Reset() {
	*x = PinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinInfo) ProtoMessage() {}

func (x *PinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinInfo.ProtoReflect.Descriptor instead.
func (*PinInfo) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{6}
}

func (x *PinInfo) GetPinType() string {
	if x != nil {
		return x.PinType
	}
	return ""
}

func (x *PinInfo) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *PinInfo) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type VerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyResp) Reset() {
	*x = VerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pin_pin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResp) ProtoMessage() {}

func (x *VerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_pin_pin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResp.ProtoReflect.Descriptor instead.
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return file_api_pin_pin_proto_rawDescGZIP(), []int{7}
}

var File_api_pin_pin_proto protoreflect.FileDescriptor

var file_api_pin_pin_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x2f, 0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69,
	0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a,
	0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x4c, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3d, 0x0a, 0x0b, 0x49, 0x73, 0x50, 0x69, 0x6e,
	0x6e, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x69,
	0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x69,
	0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x05, 0x52, 0x6d, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76,
	0x65, 0x22, 0x45, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6f,
	0x72, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x70, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x75, 0x6e, 0x70, 0x69, 0x6e, 0x22, 0x3c, 0x0a, 0x0c, 0x49, 0x73, 0x50, 0x69,
	0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73,
	0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x47, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22,
	0x0c, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x32, 0xdd, 0x02,
	0x0a, 0x03, 0x50, 0x69, 0x6e, 0x12, 0x33, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x02, 0x4c, 0x73,
	0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x2e,
	0x4c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01, 0x12, 0x41,
	0x0a, 0x08, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e,
	0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x49, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x02, 0x52, 0x6d, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70,
	0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x52, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x3c, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x30, 0x01, 0x42, 0x3f, 0x0a,
	0x0c, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70, 0x69, 0x6e, 0x50, 0x01, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x34, 0x65, 0x76, 0x65,
	0x72, 0x6c, 0x61, 0x6e, 0x64, 0x2f, 0x69, 0x70, 0x66, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x69, 0x6e, 0x3b, 0x70, 0x69, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pin_pin_proto_rawDescOnce sync.Once
	file_api_pin_pin_proto_rawDescData = file_api_pin_pin_proto_rawDesc
)

func file_api_pin_pin_proto_rawDescGZIP() []byte {
	file_api_pin_pin_proto_rawDescOnce.Do(func() {
		file_api_pin_pin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pin_pin_proto_rawDescData)
	})
	return file_api_pin_pin_proto_rawDescData
}

var file_api_pin_pin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_pin_pin_proto_goTypes = []interface{}{
	(*AddReq)(nil),        // 0: api.ipfs.pin.AddReq
	(*LsReq)(nil),         // 1: api.ipfs.pin.LsReq
	(*IsPinnedReq)(nil),   // 2: api.ipfs.pin.IsPinnedReq
	(*RmReq)(nil),         // 3: api.ipfs.pin.RmReq
	(*UpdateReq)(nil),     // 4: api.ipfs.pin.UpdateReq
	(*IsPinnedResp)(nil),  // 5: api.ipfs.pin.IsPinnedResp
	(*PinInfo)(nil),       // 6: api.ipfs.pin.PinInfo
	(*VerifyResp)(nil),    // 7: api.ipfs.pin.VerifyResp
	(*emptypb.Empty)(nil), // 8: google.protobuf.Empty
}
var file_api_pin_pin_proto_depIdxs = []int32{
	0, // 0: api.ipfs.pin.Pin.Add:input_type -> api.ipfs.pin.AddReq
	1, // 1: api.ipfs.pin.Pin.Ls:input_type -> api.ipfs.pin.LsReq
	2, // 2: api.ipfs.pin.Pin.IsPinned:input_type -> api.ipfs.pin.IsPinnedReq
	3, // 3: api.ipfs.pin.Pin.Rm:input_type -> api.ipfs.pin.RmReq
	4, // 4: api.ipfs.pin.Pin.Update:input_type -> api.ipfs.pin.UpdateReq
	8, // 5: api.ipfs.pin.Pin.Verify:input_type -> google.protobuf.Empty
	8, // 6: api.ipfs.pin.Pin.Add:output_type -> google.protobuf.Empty
	6, // 7: api.ipfs.pin.Pin.Ls:output_type -> api.ipfs.pin.PinInfo
	5, // 8: api.ipfs.pin.Pin.IsPinned:output_type -> api.ipfs.pin.IsPinnedResp
	8, // 9: api.ipfs.pin.Pin.Rm:output_type -> google.protobuf.Empty
	8, // 10: api.ipfs.pin.Pin.Update:output_type -> google.protobuf.Empty
	7, // 11: api.ipfs.pin.Pin.Verify:output_type -> api.ipfs.pin.VerifyResp
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_pin_pin_proto_init() }
func file_api_pin_pin_proto_init() {
	if File_api_pin_pin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pin_pin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPinnedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RmReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPinnedResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pin_pin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pin_pin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pin_pin_proto_goTypes,
		DependencyIndexes: file_api_pin_pin_proto_depIdxs,
		MessageInfos:      file_api_pin_pin_proto_msgTypes,
	}.Build()
	File_api_pin_pin_proto = out.File
	file_api_pin_pin_proto_rawDesc = nil
	file_api_pin_pin_proto_goTypes = nil
	file_api_pin_pin_proto_depIdxs = nil
}
