// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/4everland/ipfs-servers/app/pin/internal/conf"
	"github.com/4everland/ipfs-servers/app/pin/internal/server"
	"github.com/4everland/ipfs-servers/app/pin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	blockstore := service.NewBlockStore(data)
	datastore := service.NewDatastore(data)
	exchangeInterface := service.NewExchange(data)
	pinService, err := service.NewPinService(blockstore, datastore, exchangeInterface)
	if err != nil {
		return nil, nil, err
	}
	grpcServer := server.NewGRPCServer(confServer, pinService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
