// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/contentrouting/contentrouting.proto

package contentrouting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str []byte `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *Cid) Reset() {
	*x = Cid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contentrouting_contentrouting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cid) ProtoMessage() {}

func (x *Cid) ProtoReflect() protoreflect.Message {
	mi := &file_api_contentrouting_contentrouting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cid.ProtoReflect.Descriptor instead.
func (*Cid) Descriptor() ([]byte, []int) {
	return file_api_contentrouting_contentrouting_proto_rawDescGZIP(), []int{0}
}

func (x *Cid) GetStr() []byte {
	if x != nil {
		return x.Str
	}
	return nil
}

type ProvideReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid     *Cid `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Provide bool `protobuf:"varint,2,opt,name=provide,proto3" json:"provide,omitempty"`
}

func (x *ProvideReq) Reset() {
	*x = ProvideReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contentrouting_contentrouting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvideReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideReq) ProtoMessage() {}

func (x *ProvideReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_contentrouting_contentrouting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideReq.ProtoReflect.Descriptor instead.
func (*ProvideReq) Descriptor() ([]byte, []int) {
	return file_api_contentrouting_contentrouting_proto_rawDescGZIP(), []int{1}
}

func (x *ProvideReq) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *ProvideReq) GetProvide() bool {
	if x != nil {
		return x.Provide
	}
	return false
}

type GetProvidersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid   *Cid  `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetProvidersReq) Reset() {
	*x = GetProvidersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contentrouting_contentrouting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProvidersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersReq) ProtoMessage() {}

func (x *GetProvidersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_contentrouting_contentrouting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersReq.ProtoReflect.Descriptor instead.
func (*GetProvidersReq) Descriptor() ([]byte, []int) {
	return file_api_contentrouting_contentrouting_proto_rawDescGZIP(), []int{2}
}

func (x *GetProvidersReq) GetCid() *Cid {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *GetProvidersReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Multiaddr [][]byte `protobuf:"bytes,2,rep,name=multiaddr,proto3" json:"multiaddr,omitempty"`
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_contentrouting_contentrouting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_contentrouting_contentrouting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_api_contentrouting_contentrouting_proto_rawDescGZIP(), []int{3}
}

func (x *AddrInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddrInfo) GetMultiaddr() [][]byte {
	if x != nil {
		return x.Multiaddr
	}
	return nil
}

var File_api_contentrouting_contentrouting_proto protoreflect.FileDescriptor

var file_api_contentrouting_contentrouting_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x70, 0x66, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x03, 0x43,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x74, 0x72, 0x22, 0x52, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x2a, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43, 0x69, 0x64, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x22, 0x53, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x2a, 0x0a, 0x03, 0x63,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69,
	0x70, 0x66, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x43,
	0x69, 0x64, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a,
	0x08, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x32, 0xb1, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x42, 0x0a, 0x07, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5b,
	0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x41,
	0x73, 0x79, 0x6e, 0x63, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x30, 0x01, 0x42, 0x4c, 0x0a, 0x18, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x01, 0x5a, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x3b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_contentrouting_contentrouting_proto_rawDescOnce sync.Once
	file_api_contentrouting_contentrouting_proto_rawDescData = file_api_contentrouting_contentrouting_proto_rawDesc
)

func file_api_contentrouting_contentrouting_proto_rawDescGZIP() []byte {
	file_api_contentrouting_contentrouting_proto_rawDescOnce.Do(func() {
		file_api_contentrouting_contentrouting_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_contentrouting_contentrouting_proto_rawDescData)
	})
	return file_api_contentrouting_contentrouting_proto_rawDescData
}

var file_api_contentrouting_contentrouting_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_contentrouting_contentrouting_proto_goTypes = []interface{}{
	(*Cid)(nil),             // 0: api.ipfs.blockstore.Cid
	(*ProvideReq)(nil),      // 1: api.ipfs.blockstore.ProvideReq
	(*GetProvidersReq)(nil), // 2: api.ipfs.blockstore.GetProvidersReq
	(*AddrInfo)(nil),        // 3: api.ipfs.blockstore.AddrInfo
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_api_contentrouting_contentrouting_proto_depIdxs = []int32{
	0, // 0: api.ipfs.blockstore.ProvideReq.cid:type_name -> api.ipfs.blockstore.Cid
	0, // 1: api.ipfs.blockstore.GetProvidersReq.cid:type_name -> api.ipfs.blockstore.Cid
	1, // 2: api.ipfs.blockstore.ContentRouting.Provide:input_type -> api.ipfs.blockstore.ProvideReq
	2, // 3: api.ipfs.blockstore.ContentRouting.FindProvidersAsync:input_type -> api.ipfs.blockstore.GetProvidersReq
	4, // 4: api.ipfs.blockstore.ContentRouting.Provide:output_type -> google.protobuf.Empty
	3, // 5: api.ipfs.blockstore.ContentRouting.FindProvidersAsync:output_type -> api.ipfs.blockstore.AddrInfo
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_contentrouting_contentrouting_proto_init() }
func file_api_contentrouting_contentrouting_proto_init() {
	if File_api_contentrouting_contentrouting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_contentrouting_contentrouting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contentrouting_contentrouting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvideReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contentrouting_contentrouting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProvidersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_contentrouting_contentrouting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_contentrouting_contentrouting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_contentrouting_contentrouting_proto_goTypes,
		DependencyIndexes: file_api_contentrouting_contentrouting_proto_depIdxs,
		MessageInfos:      file_api_contentrouting_contentrouting_proto_msgTypes,
	}.Build()
	File_api_contentrouting_contentrouting_proto = out.File
	file_api_contentrouting_contentrouting_proto_rawDesc = nil
	file_api_contentrouting_contentrouting_proto_goTypes = nil
	file_api_contentrouting_contentrouting_proto_depIdxs = nil
}
