// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/4everland/ipfs-servers/app/gateway/conf"
	"github.com/4everland/ipfs-servers/app/gateway/server"
	"github.com/4everland/ipfs-servers/app/gateway/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	blockstore := service.NewBlockStore(data)
	unixfsAPI := service.NewUnixfs(blockstore)
	valueStore := service.NewRouting()
	blocksGateway, err := service.NewBlocksGateway(blockstore, unixfsAPI, valueStore)
	if err != nil {
		return nil, nil, err
	}
	httpServer := server.NewGatewayServer(confServer, blocksGateway, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
