// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: tasks/conf/config.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3        *S3        `protobuf:"bytes,1,opt,name=s3,proto3" json:"s3,omitempty"`
	Arseeding *Arseeding `protobuf:"bytes,2,opt,name=arseeding,proto3" json:"arseeding,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_conf_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_conf_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_tasks_conf_config_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetS3() *S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Data) GetArseeding() *Arseeding {
	if x != nil {
		return x.Arseeding
	}
	return nil
}

type S3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint  string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region    string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket    string `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKey string `protobuf:"bytes,4,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey string `protobuf:"bytes,5,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Schemes   string `protobuf:"bytes,6,opt,name=schemes,proto3" json:"schemes,omitempty"`
}

func (x *S3) Reset() {
	*x = S3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_conf_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3) ProtoMessage() {}

func (x *S3) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_conf_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3.ProtoReflect.Descriptor instead.
func (*S3) Descriptor() ([]byte, []int) {
	return file_tasks_conf_config_proto_rawDescGZIP(), []int{1}
}

func (x *S3) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *S3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *S3) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *S3) GetSchemes() string {
	if x != nil {
		return x.Schemes
	}
	return ""
}

type Arseeding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayAddr string `protobuf:"bytes,1,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	Mnemonic    string `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
}

func (x *Arseeding) Reset() {
	*x = Arseeding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_conf_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arseeding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arseeding) ProtoMessage() {}

func (x *Arseeding) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_conf_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arseeding.ProtoReflect.Descriptor instead.
func (*Arseeding) Descriptor() ([]byte, []int) {
	return file_tasks_conf_config_proto_rawDescGZIP(), []int{2}
}

func (x *Arseeding) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

func (x *Arseeding) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

var File_tasks_conf_config_proto protoreflect.FileDescriptor

var file_tasks_conf_config_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x5b, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a,
	0x02, 0x73, 0x33, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x53, 0x33, 0x52, 0x02, 0x73, 0x33, 0x12, 0x33, 0x0a,
	0x09, 0x61, 0x72, 0x73, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x72,
	0x73, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x61, 0x72, 0x73, 0x65, 0x65, 0x64, 0x69,
	0x6e, 0x67, 0x22, 0xa6, 0x01, 0x0a, 0x02, 0x53, 0x33, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x09, 0x41,
	0x72, 0x73, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x41, 0x64, 0x64, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x70, 0x66, 0x73, 0x2d,
	0x74, 0x6f, 0x70, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63,
	0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tasks_conf_config_proto_rawDescOnce sync.Once
	file_tasks_conf_config_proto_rawDescData = file_tasks_conf_config_proto_rawDesc
)

func file_tasks_conf_config_proto_rawDescGZIP() []byte {
	file_tasks_conf_config_proto_rawDescOnce.Do(func() {
		file_tasks_conf_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_tasks_conf_config_proto_rawDescData)
	})
	return file_tasks_conf_config_proto_rawDescData
}

var file_tasks_conf_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tasks_conf_config_proto_goTypes = []interface{}{
	(*Data)(nil),      // 0: tasks.conf.Data
	(*S3)(nil),        // 1: tasks.conf.S3
	(*Arseeding)(nil), // 2: tasks.conf.Arseeding
}
var file_tasks_conf_config_proto_depIdxs = []int32{
	1, // 0: tasks.conf.Data.s3:type_name -> tasks.conf.S3
	2, // 1: tasks.conf.Data.arseeding:type_name -> tasks.conf.Arseeding
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tasks_conf_config_proto_init() }
func file_tasks_conf_config_proto_init() {
	if File_tasks_conf_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tasks_conf_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_conf_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_conf_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arseeding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tasks_conf_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasks_conf_config_proto_goTypes,
		DependencyIndexes: file_tasks_conf_config_proto_depIdxs,
		MessageInfos:      file_tasks_conf_config_proto_msgTypes,
	}.Build()
	File_tasks_conf_config_proto = out.File
	file_tasks_conf_config_proto_rawDesc = nil
	file_tasks_conf_config_proto_goTypes = nil
	file_tasks_conf_config_proto_depIdxs = nil
}
