// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/4everland/ipfs-top/app/provide/internal/conf"
	"github.com/4everland/ipfs-top/app/provide/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	consumerGroup := server.NewConsumer(data)
	v := server.NewNodes(data)
	v2 := server.NewRPC(data)
	eventServer := server.NewEventServer(data, consumerGroup, v, v2)
	blockstore := server.NewBlockStore(data)
	reproviderServer := server.NewReproviderServer(blockstore, v, v2)
	app := newApp(logger, eventServer, reproviderServer)
	return app, func() {
	}, nil
}
