// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/4everland/ipfs-top/app/provide/internal/conf"
	"github.com/4everland/ipfs-top/app/provide/internal/data"
	"github.com/4everland/ipfs-top/app/provide/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init task receiver server application.
func wireApp(confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	consumerGroup := server.NewConsumer(confData)
	v := server.NewNodes(confData)
	eventServer := server.NewEventServer(confData, consumerGroup, v)
	blockstore := server.NewBlockStore(confData)
	db := data.NewGormClient(confData, logger)
	pinSetRepo := data.NewDataSetRepo(db, logger)
	reproviderServer := server.NewReproviderServer(blockstore, v, pinSetRepo, logger)
	app := newApp(logger, eventServer, reproviderServer)
	return app, func() {
	}, nil
}
