// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: app/pin/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_DBType int32

const (
	Data_LevelDB Data_DBType = 0
	Data_TiKV    Data_DBType = 1
)

// Enum value maps for Data_DBType.
var (
	Data_DBType_name = map[int32]string{
		0: "LevelDB",
		1: "TiKV",
	}
	Data_DBType_value = map[string]int32{
		"LevelDB": 0,
		"TiKV":    1,
	}
)

func (x Data_DBType) Enum() *Data_DBType {
	p := new(Data_DBType)
	*p = x
	return p
}

func (x Data_DBType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_DBType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_pin_internal_conf_conf_proto_enumTypes[0].Descriptor()
}

func (Data_DBType) Type() protoreflect.EnumType {
	return &file_app_pin_internal_conf_conf_proto_enumTypes[0]
}

func (x Data_DBType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_DBType.Descriptor instead.
func (Data_DBType) EnumDescriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data   *Data   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grpc *Server_GRPC `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockstoreUri    string          `protobuf:"bytes,1,opt,name=blockstore_uri,json=blockstoreUri,proto3" json:"blockstore_uri,omitempty"`
	ExchangeEndpoint string          `protobuf:"bytes,2,opt,name=exchange_endpoint,json=exchangeEndpoint,proto3" json:"exchange_endpoint,omitempty"`
	Datastore        *Data_Datastore `protobuf:"bytes,3,opt,name=datastore,proto3" json:"datastore,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetBlockstoreUri() string {
	if x != nil {
		return x.BlockstoreUri
	}
	return ""
}

func (x *Data) GetExchangeEndpoint() string {
	if x != nil {
		return x.ExchangeEndpoint
	}
	return ""
}

func (x *Data) GetDatastore() *Data_Datastore {
	if x != nil {
		return x.Datastore
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    string               `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Network string               `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Timeout *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Datastore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Data_DBType             `protobuf:"varint,1,opt,name=type,proto3,enum=ipfs.rpc.conf.Data_DBType" json:"type,omitempty"`
	Leveldb *Data_Datastore_LevelDB `protobuf:"bytes,2,opt,name=leveldb,proto3" json:"leveldb,omitempty"`
	Tikv    *Data_Datastore_TiKV    `protobuf:"bytes,3,opt,name=tikv,proto3" json:"tikv,omitempty"`
}

func (x *Data_Datastore) Reset() {
	*x = Data_Datastore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Datastore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Datastore) ProtoMessage() {}

func (x *Data_Datastore) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Datastore.ProtoReflect.Descriptor instead.
func (*Data_Datastore) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Datastore) GetType() Data_DBType {
	if x != nil {
		return x.Type
	}
	return Data_LevelDB
}

func (x *Data_Datastore) GetLeveldb() *Data_Datastore_LevelDB {
	if x != nil {
		return x.Leveldb
	}
	return nil
}

func (x *Data_Datastore) GetTikv() *Data_Datastore_TiKV {
	if x != nil {
		return x.Tikv
	}
	return nil
}

type Data_Datastore_LevelDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Data_Datastore_LevelDB) Reset() {
	*x = Data_Datastore_LevelDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Datastore_LevelDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Datastore_LevelDB) ProtoMessage() {}

func (x *Data_Datastore_LevelDB) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Datastore_LevelDB.ProtoReflect.Descriptor instead.
func (*Data_Datastore_LevelDB) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Data_Datastore_LevelDB) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Data_Datastore_TiKV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *Data_Datastore_TiKV) Reset() {
	*x = Data_Datastore_TiKV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pin_internal_conf_conf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data_Datastore_TiKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Datastore_TiKV) ProtoMessage() {}

func (x *Data_Datastore_TiKV) ProtoReflect() protoreflect.Message {
	mi := &file_app_pin_internal_conf_conf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Datastore_TiKV.ProtoReflect.Descriptor instead.
func (*Data_Datastore_TiKV) Descriptor() ([]byte, []int) {
	return file_app_pin_internal_conf_conf_proto_rawDescGZIP(), []int{2, 0, 1}
}

func (x *Data_Datastore_TiKV) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

var File_app_pin_internal_conf_conf_proto protoreflect.FileDescriptor

var file_app_pin_internal_conf_conf_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x69, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70,
	0x12, 0x2f, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa5, 0x01, 0x0a,
	0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x04, 0x67, 0x72, 0x70, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64,
	0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x52, 0x50, 0x43, 0x52, 0x04, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x69, 0x0a, 0x04, 0x47, 0x52, 0x50,
	0x43, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x33, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x22, 0xb4, 0x03, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a,
	0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x75, 0x72, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x55, 0x72, 0x69, 0x12, 0x2b, 0x0a, 0x11, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x3d, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65,
	0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x1a, 0xf7, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x30,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x69,
	0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x44, 0x42, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x41, 0x0a, 0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x64, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x42, 0x52, 0x07, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x64, 0x62, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x69, 0x6b, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x54, 0x69, 0x4b, 0x56, 0x52, 0x04, 0x74, 0x69, 0x6b, 0x76, 0x1a, 0x1d, 0x0a,
	0x07, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x42, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x1a, 0x1c, 0x0a, 0x04,
	0x54, 0x69, 0x4b, 0x56, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x22, 0x1f, 0x0a, 0x06, 0x44, 0x42,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x44, 0x42, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x69, 0x4b, 0x56, 0x10, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x69,
	0x70, 0x66, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x64, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_pin_internal_conf_conf_proto_rawDescOnce sync.Once
	file_app_pin_internal_conf_conf_proto_rawDescData = file_app_pin_internal_conf_conf_proto_rawDesc
)

func file_app_pin_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_app_pin_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_app_pin_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_pin_internal_conf_conf_proto_rawDescData)
	})
	return file_app_pin_internal_conf_conf_proto_rawDescData
}

var file_app_pin_internal_conf_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_pin_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_pin_internal_conf_conf_proto_goTypes = []interface{}{
	(Data_DBType)(0),               // 0: ipfs.rpc.conf.Data.DBType
	(*Bootstrap)(nil),              // 1: ipfs.rpc.conf.Bootstrap
	(*Server)(nil),                 // 2: ipfs.rpc.conf.Server
	(*Data)(nil),                   // 3: ipfs.rpc.conf.Data
	(*Server_GRPC)(nil),            // 4: ipfs.rpc.conf.Server.GRPC
	(*Data_Datastore)(nil),         // 5: ipfs.rpc.conf.Data.Datastore
	(*Data_Datastore_LevelDB)(nil), // 6: ipfs.rpc.conf.Data.Datastore.LevelDB
	(*Data_Datastore_TiKV)(nil),    // 7: ipfs.rpc.conf.Data.Datastore.TiKV
	(*durationpb.Duration)(nil),    // 8: google.protobuf.Duration
}
var file_app_pin_internal_conf_conf_proto_depIdxs = []int32{
	2, // 0: ipfs.rpc.conf.Bootstrap.server:type_name -> ipfs.rpc.conf.Server
	3, // 1: ipfs.rpc.conf.Bootstrap.data:type_name -> ipfs.rpc.conf.Data
	4, // 2: ipfs.rpc.conf.Server.grpc:type_name -> ipfs.rpc.conf.Server.GRPC
	5, // 3: ipfs.rpc.conf.Data.datastore:type_name -> ipfs.rpc.conf.Data.Datastore
	8, // 4: ipfs.rpc.conf.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	0, // 5: ipfs.rpc.conf.Data.Datastore.type:type_name -> ipfs.rpc.conf.Data.DBType
	6, // 6: ipfs.rpc.conf.Data.Datastore.leveldb:type_name -> ipfs.rpc.conf.Data.Datastore.LevelDB
	7, // 7: ipfs.rpc.conf.Data.Datastore.tikv:type_name -> ipfs.rpc.conf.Data.Datastore.TiKV
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_app_pin_internal_conf_conf_proto_init() }
func file_app_pin_internal_conf_conf_proto_init() {
	if File_app_pin_internal_conf_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_pin_internal_conf_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server_GRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Datastore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Datastore_LevelDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pin_internal_conf_conf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data_Datastore_TiKV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_pin_internal_conf_conf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_pin_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_app_pin_internal_conf_conf_proto_depIdxs,
		EnumInfos:         file_app_pin_internal_conf_conf_proto_enumTypes,
		MessageInfos:      file_app_pin_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_app_pin_internal_conf_conf_proto = out.File
	file_app_pin_internal_conf_conf_proto_rawDesc = nil
	file_app_pin_internal_conf_conf_proto_goTypes = nil
	file_app_pin_internal_conf_conf_proto_depIdxs = nil
}
